
service: sls-lambda-todos

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'dev'}


functions:
  todo:
    handler: handler.todo
    layers:
    #Dynamic reference of Logging Layer ARN
      - ${cf:layers-${self:provider.stage}.LoggingLayerExport}

    events:
      - http:
          path: todo
          method: get
